### PR TITLE
Fixes #14684 - Save end time for recurring

### PR DESCRIPTION
**Pull request by adamruzicka**
- [x] Requires https://github.com/theforeman/foreman-tasks/pull/183

### CODE REVIEW

**Comment by ares** [comment]
It does not seem to work for me, when I set end time, the action results in 200 but it redirects me back to the invocation form without any error. Also it creates the job, it creates recurring action but it does not create the task so the job is queued forever. I don't see any error in the log.

**Comment by ares** [comment]
After short debugging session we realized that if there's no window for job to start, task is not created causing all of this problems. So a validation should be added that checks that $start_time < $end_time

**Comment by adamruzicka** [comment]
[test]

**Comment by adamruzicka** [comment]
Wasn't there a specific need for doing it this way? Something like it was needed to force validation of all of the template invocations (which the all? approach wouldn't do)?

**Comment by ares** [comment]
ah right, `.all?` is lazy :bulb: thanks!

**Comment by adamruzicka** [comment]
Great, glad we didn't miss it

**Comment by iNecas** [comment]
Foreman-tasks 0.7.17 with required change was just released

**Comment by adamruzicka** [comment]
Let's see how the [test] goes

**Comment by adamruzicka** [comment]
[test]

**Comment by adamruzicka** [comment]
[test]

**Comment by ares** [comment]
Works fine, thanks @adamruzicka, merging!

**Comment by ares** [comment]
oops I left double comment in commit message, sorry :-)

**Pull request merged**
