### PR TITLE
[Foreman 1.11] fixes #12312 - bulk actions opens job invocation in new page directly

### PR DESCRIPTION
**Pull request by stbenjam**
Requires https://github.com/theforeman/foreman/pull/2892

### CODE REVIEW

**Comment by adamruzicka** [comment]
Works as expected

**Comment by dLobatog** [comment]
This can be merged already

**Comment by stbenjam** [comment]
As soon as someone reviews + ACK's it :)

**Comment by stbenjam** [comment]
It's also been some months since this was [test]ed, let's make sure it's OK.

**Comment by stbenjam** [comment]
@iNecas @ares Last one, can we get this in and I'll do 0.3.0 today?

**Comment by iNecas** [comment]
ACK - tested and worked well!

**Comment by iNecas** [comment]
:fireworks:

**Comment by stbenjam** [comment]
Thanks!

**Pull request merged**
