### PR TITLE
Fixes #34970 - Allow enabling REX pull in registration form

### PR DESCRIPTION
**Pull request by adamruzicka**
Requires:
- https://github.com/theforeman/foreman/pull/9235

### CODE REVIEW

**Comment by adamruzicka** [comment]
@MariaAga any idea about the tests?

**Comment by MariaAga** [comment]
Yup, JS tests are still broken from last week and in progress of getting fixed

**Review by stejskalleos — CHANGES_REQUESTED** [review]

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**, works as expected.

**Comment by stejskalleos** [comment]
I see that `Ruby / test_ruby` job is failing, not sure if it is related to this PR but it would be nice to have green run before the merge

**Review by stejskalleos — APPROVED** [review]

**Comment by adamruzicka** [comment]
Thank you @stejskalleos !

**Pull request merged**
