### PR TITLE
Fixes #17814 - do not auto complete on logic id

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ohadlevy** [comment]
:+1: assuming tests pass.

**Comment by dLobatog** [comment]
It fixes the issue for me too

**Comment by ohadlevy** [comment]
[test]

**Comment by ares** [comment]
[test]

**Comment by adamruzicka** [comment]
[test]

**Comment by adamruzicka** [comment]
[test]

**Comment by adamruzicka** [comment]
Merged, thanks @ares

**Pull request merged**
