### PR TITLE
Fixes #32065 - Undeclared :error_message instance field

### PR DESCRIPTION
**Pull request by domq**
Fixes [#32065](https://projects.theforeman.org/issues/32065)

### CODE REVIEW

**Comment by adamruzicka** [comment]
Thanks for the patch it seems to work well. Just out of curiosity, how do other template types deal with this?

**Comment by domq** [comment]
I didn't do the required archaeology, but I thought that perhaps job templates used to inherit a `:error_message` field from their superclass but don't anymore? Really I'm not sure.

**Review by adamruzicka — APPROVED** [review]
Fixes the issue for me, ACK

**Comment by adamruzicka** [comment]
Thank you @domq !

**Pull request merged**
