### PR TITLE
Fixes #11406 - Rename Ssh to SSH

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by stbenjam** [comment]
Do you think it's worth renaming the provider's key too for consistency's sake? https://github.com/theforeman/foreman_remote_execution/blob/master/lib/foreman_remote_execution/engine.rb#L152

**Comment by stbenjam** [comment]
It also looks like `with_features` is case-sensitive, so this thingy doesn't return any proxies for the tests which still use Ssh in a few places. https://github.com/theforeman/foreman_remote_execution/blob/master/app/models/concerns/foreman_remote_execution/host_extensions.rb#L43

**Comment by ares** [comment]
right, I renamed it everywhere except proxy action name, could you please give it another look? (note that you have to rerun the migration since the provider type of job template has been changed as well)

**Comment by stbenjam** [comment]
Awesome! Tested and works great, ACK

**Comment by ares** [comment]
Thanks for review, merging!

**Pull request merged**
