### PR TITLE
Fixes #20101 - update input template renderer for Foreman 1.16

### PR DESCRIPTION
**Pull request by iNecas**
It keeps backward compatibility with Foreman 1.15.

While searching for older version compatibility checks, I've removed
really old ones.

### CODE REVIEW

**Comment by iNecas** [comment]
The tests are running at http://ci.theforeman.org/job/test_plugin_pull_request/3839/

**Comment by adamruzicka** [comment]
Opened PR for the rubocop failure https://github.com/iNecas/foreman_remote_execution/pull/4

**Comment by iNecas** [comment]
https://github.com/iNecas/foreman_remote_execution/pull/4 merged, and the test with this version are as gree as possible http://ci.theforeman.org/job/test_plugin_pull_request/3840/

**Comment by adamruzicka** [comment]
Merged, thanks @iNecas

**Pull request merged**
