### PR TITLE
Fixes #30582 - host search filter does not work in job invocation page

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by adamruzicka** [comment]
When I type a search query into the search box and press enter, nothing happens, I have to hit the search button with mouse. Is this something that we could easily fix as part of this?

**Comment by stejskalleos** [comment]
> When I type a search query into the search box and press enter, nothing happens, I have to hit the search button with mouse. Is this something that we could easily fix as part of this?

This is a bug what was there before - I tried REX 3.2.2 and it have same behavior. I didn't touched search & pagination at all - see https://github.com/theforeman/foreman_remote_execution/pull/493/files#diff-3aa3b6670498f9ab916dca652df18dbb

In next version it's fixed, search bar and pagination is full react, however after quick look I wasn't able to find solution how to fix it easily.

**Comment by adamruzicka** [comment]
Fair enough

**Comment by adamruzicka** [comment]
Thank you @stejskalleos !

**Pull request merged**
