### PR TITLE
Fixes #19046 - skip unknown feature attribute in migration

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
This is likely a release blocker

**Comment by dLobatog** [comment]
Works well with Katello:master - https://gist.github.com/e6602f6b9aa0039d1beb5f449ef99403 (the last db:migrate in the gist is *after* applying the patch here)

**Comment by adamruzicka** [comment]
Test failures unrelated, merging

**Comment by adamruzicka** [comment]
Thanks @ares

**Pull request merged**
