### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by iNecas** [comment]
When looking at https://github.com/stbenjam/foreman_remote_execution/tree/README, I don't see the badges? It will start working after merging or this is an issue with the img service? I see also https://github.com/theforeman/foreman_salt not working with badges properly

**Comment by stbenjam** [comment]
Maybe related to the GitHub DDoS? They were working yesterday.

**Comment by stbenjam** [comment]
They're working as of now

**Comment by iNecas** [comment]
Thanks!

**Pull request merged**
