### PR TITLE
Fixes #11145 - template invocations are destroyed with template

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by iNecas** [comment]
Tests? We do so for other deletions https://github.com/theforeman/foreman_remote_execution/blob/master/test/unit/targeting_test.rb#L57

**Comment by ares** [comment]
Here you are, rebase is for free.

**Comment by ares** [comment]
yet another rebase

**Comment by iNecas** [comment]
```doge
very green
            much like
   such ack
         wow
```

**Comment by ares** [comment]
Thanks, merging

**Pull request merged**
