### PR TITLE
Fixes #13148 - style statistics as on report page

### PR DESCRIPTION
**Pull request by ares**
before
tables3
after
tables4

### CODE REVIEW

**Comment by stbenjam** [comment]
I'm not sure I really like the Foreman reports page index, but at least it looks consistent.  The only thing I'm not sure about is these N/A's.

**Comment by stbenjam** [comment]
How about dashes?

foo

**Comment by ares** [comment]
Dashes seems a bit better, maybe we could use one column with the statistics that @dLobatog adds in the job invocation detail under the chart. But yeah, it wouldn't be consistent with reports so maybe we should change it there first.

**Comment by ohadlevy** [comment]
:+1: to fix on both places, I wasnt too happy with the reports page in
foreman after patternfly either.

**Comment by stbenjam** [comment]
Looks good, although I think I prefer `&mdash;` to the double `--`

**Comment by ares** [comment]
right, changed to `&mdash;`

**Comment by stbenjam** [comment]
:+1: ACK

**Comment by ares** [comment]
Thanks, merging

**Pull request merged**
