### PR TITLE
fixes #13203 - use single quotes on string literals

### PR DESCRIPTION
**Pull request by stbenjam**
I'd like to enable this cop :cop:, single quotes make me happy

### CODE REVIEW

**Comment by adamruzicka** [comment]
Shouldn't we convert double quotes to single in ruby blocks in erb templates too (even though there's no cop for that)?

**Comment by ares** [comment]
yes, great cop! :smile_cat:
@iNecas would you be OK with it?

erb would be nice as well but if no cop will watch that I'm sure it won't last

**Comment by iNecas** [comment]
No problem with me

**Comment by ares** [comment]
hehe, you fixed even our docs tools :-) please rebase, I'll merge this as first as it is easy to have conflict with others

**Comment by stbenjam** [comment]
> hehe, you fixed even our docs tools :-) 

Rubocop did :-) Just a `rubocop --only Style/StringLiterals -a` and a quick scan to make sure it didn't muck anything up

> please rebase, I'll merge this as first as it is easy to have conflict with others

Rebased!

**Comment by ares** [comment]
Thanks @stbenjam, merging!

**Comment by stbenjam** [comment]
Thanks!!

**Pull request merged**
