### PR TITLE
Fixes #25991 - provide puppet run feature

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
so it fails because it can't find rex feature 'puppet_run_host', I wonder how that is possible if we register it in engine.rb?

**Comment by iNecas** [comment]
https://github.com/inecas/foreman/blob/548c23f1280ec8ee48d40c0e0bf4f9ccbe960e5f/test/unit/tasks/seeds_test.rb#L11

**Comment by adamruzicka** [comment]
@ares what's the status here?

**Comment by ares** [comment]
No time to finish, I suppose just some small test update is missing.

**Comment by adamruzicka** [comment]
The test failures seem to be related to https://github.com/theforeman/foreman_remote_execution/pull/415 . Could you please rebase?

**Comment by adamruzicka** [comment]
I took the liberty of rebasing this, let's see that Jenkins thinks.

**Comment by adamruzicka** [comment]
Test failures are related

**Comment by adamruzicka** [comment]
@ares Guess we need to do something similar to what foreman ansbile does https://github.com/theforeman/foreman_ansible/blob/master/db/seeds.d/75_job_templates.rb#L7

**Comment by adamruzicka** [comment]
I opened https://github.com/theforeman/foreman_remote_execution/pull/420 which is based on this PR and fixes the broken tests, I'm going to go ahead and close this one

**Pull request closed without merging**
