### PR TITLE
Fixes #12815 - unify start time information

### PR DESCRIPTION
**Pull request by ares**
While it's not blocked by https://github.com/theforeman/foreman-tasks/pull/161 it would be better to get that one in first, I'd remove the TODO and use delegate instead. We'll see how fast would that PR get in, but it shouldn't blocking the review.

### CODE REVIEW

**Comment by ares** [comment]
I'll rebase one new foreman-tasks so we can use the delegate

**Comment by ares** [comment]
rebased using new foreman-tasks, ready for reviewing

**Comment by stbenjam** [comment]
Looks good, ACK

**Comment by ares** [comment]
Thanks, merging.

**Pull request merged**
