### PR TITLE
Fixes #12024 - balancer recovers if no proxy is usable

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
@stbenjam would you mind reviewing?

**Comment by stbenjam** [comment]
Oh, didn't realize min_by could return nil there.  Looks good - can you add a test?

**Comment by ares** [comment]
sure, added

**Comment by stbenjam** [comment]
APJ

**Comment by ares** [comment]
Result is read because of rubocop findings in already merged code. I disable the cop since I don't see anything wrong with using inject (it suggests to use each_with_object instead)

```
Offenses:

/var/lib/workspace/workspace/test_plugin_pull_request/database/postgresql/label/fast/ruby/1.9.3/plugin/app/services/proxy_load_balancer.rb:19:13: C: Use each_with_object instead of inject.
    proxies.inject({}) do |result, proxy|
            ^^^^^^
```

**Comment by stbenjam** [comment]
Rubocop weirdness, it was green on the PR that added the inject.

Anyway,  APJ.

**Comment by ares** [comment]
It's green, thanks for review!

**Pull request merged**
