### PR TITLE
Fixes #28348 - Register assets for precompilation

### PR DESCRIPTION
**Pull request by adamruzicka**
Recent commit 2bf43ec changes the way how we register assets for precompilation.
Sadly, this change caused plugin:assets:precompile[$plugin] rake task to ignore
certain assets for remote execution by disabling automatic asset detection.
This commit keeps the automatic detection disabled, but registers a list of
assets which should be precompiled.

### CODE REVIEW

**Comment by adamruzicka** [comment]
@ezr-ondrej How does this look?

**Comment by ares** [comment]
I guess it's twice because we want it working in packaging and in dev setup, right?

**Comment by adamruzicka** [comment]
In packaging we use the `plugin:assets:precompile[$plugin]`, sadly it doesn't seem to process assets which are not registered in `Foreman::Plugin::Assets` registry and completely ignores `app.config.assets.precompile`

**Comment by ares** [comment]
Thanks @adamruzicka, merging!

**Pull request merged**
