### PR TITLE
Fixes #34471 - Add bookmarks to jobs targeting host

### PR DESCRIPTION
**Pull request by MariaAga**
Uses the same hack to fill the search input text as the job wizard using `getResults`

### CODE REVIEW

**Comment by adamruzicka** [comment]
Rubocop failures should be unrelated and already fixed in master. Could you rebase so it goes away?

**Comment by MariaAga** [comment]
Working on a fix for this in core instead: https://projects.theforeman.org/issues/34546

**Comment by MariaAga** [comment]
Added also a small fix to pagination so when users move between bookmarks (and searches) the page will reset to 1

**Comment by adamruzicka** [comment]
Unless I'm missing something then when I select a bookmark, it indeed filters the table, but there is no indication anywhere why.  I'm not saying it is wrong, just confusing. The search bar remains as it was and when I open the bookmarks again, it doesn't show that any of the bookmarks is selected.

**Comment by MariaAga** [comment]
If you dont see text in the searchbar then maybe foreman core is out of date, it should have this pr in: https://github.com/theforeman/foreman/pull/9156
or is it a different issue?

> I open the bookmarks again, it doesn't show that any of the bookmarks is selected.

isn't this the normal behavior in all the bookmarks in foreman?

**Comment by adamruzicka** [comment]
> maybe foreman core is out of date, it should have this pr in: https://github.com/theforeman/foreman/pull/9156

Yeah, I didn't have that... Please disregard my previous comment

**Comment by MariaAga** [comment]
@Ron-Lavi can you take a look?

**Review by adamruzicka — APPROVED** [review]
Looks good

**Comment by adamruzicka** [comment]
Thank you @MariaAga !

**Pull request merged**
