### PR TITLE
Fixes #33094 - auto fill job wizard with hosts

### PR DESCRIPTION
**Pull request by MariaAga**
url example to get fill: 
`/experimental/job_wizard?host_ids%5B%5D=100&host_ids%5B%5D=67`
`/experimental/job_wizard?search=os+%3D+CentOS`
depends on: https://github.com/theforeman/foreman_remote_execution/pull/578

### CODE REVIEW

**Comment by MariaAga** [comment]
Thanks @laviro! are any more changes needed?

**Review by laviro — APPROVED** [review]
Thanks @MariaAga !

**Review by adamruzicka — APPROVED** [review]
Works nicely, ACK

**Comment by adamruzicka** [comment]
Thank you @MariaAga & @laviro !

**Pull request merged**
