### PR TITLE
Fixes #21272 - Unscoped templates

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by ares** [comment]
I wonder if user should see such template invocations in the first place. How is this issue triggered?

**Comment by adamruzicka** [comment]
Someone encountered this after upgrading satellite. Job Templates didn't have any orgs/locs assigned and accessing a job from before the upgrade would raise the undefined method error

**Comment by iNecas** [comment]
[test]

**Comment by ares** [comment]
Ok, sounds reasonable

**Comment by iNecas** [comment]
Test failures unrelated (filed an issue and proposed fix for that in infra http://projects.theforeman.org/issues/21318). Thanks @adamruzicka

**Pull request merged**
