### PR TITLE
Fixes #17456 - save the feature only if changed

### PR DESCRIPTION
**Pull request by iNecas**
Slightly improved version of
https://github.com/theforeman/foreman_remote_execution/pull/211 + added tests

### CODE REVIEW

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
[test]

**Comment by adamruzicka** [comment]
[test]

**Comment by adamruzicka** [comment]
Merged, thanks @iNecas & @xgazdi

**Pull request merged**
