### PR TITLE
Fixes #33087 - Add password options to hammer REX job

### PR DESCRIPTION
**Pull request by pkoprda**
Add options for setting sudo password and ssh password when creating REX job using hammer

### CODE REVIEW

**Review by adamruzicka — CHANGES_REQUESTED** [review]
Effective user password is ignored. It gets sent over to the server, but then I gets removed here https://github.com/theforeman/foreman_remote_execution/blob/master/app/controllers/api/v2/job_invocations_controller.rb#L200

**Comment by pkoprda** [comment]
Thanks for your review @adamruzicka :+1: Let me know if anything else is needed

**Review by adamruzicka — COMMENTED** [review]
While you're at it, could you also add support for providing key passphrase?

**Review by adamruzicka — APPROVED** [review]
Works well, ACK

**Comment by adamruzicka** [comment]
Thank you @pkoprda !

**Pull request merged**
