### PR TITLE
Fixes #30628 - show empty hosts in job invocation api

### PR DESCRIPTION
**Pull request by MariaAga**
based on the solution here: https://github.com/nesquena/rabl/issues/166

### CODE REVIEW

**Comment by adamruzicka** [comment]
Could you add a test? There have been too many bugs for such a simple thing

**Comment by MariaAga** [comment]
Changed a test to check that it's an empty array and not just 'empty'

**Comment by adamruzicka** [comment]
Thank you @MariaAga ! Could you please open a cherrypick (with -x) against `3.3-stable`?

**Comment by MariaAga** [comment]
https://github.com/theforeman/foreman_remote_execution/pull/526 @adamruzicka

**Pull request merged**
