### PR TITLE
added asserts to template details test

### PR DESCRIPTION
**Pull request by pondrejk**
related to https://bugzilla.redhat.com/show_bug.cgi?id=1539042

### CODE REVIEW

**Comment by iNecas** [comment]
ok to test

**Comment by iNecas** [comment]
Running tests at http://ci.theforeman.org/job/test_plugin_pull_request/4830/

**Comment by mmoll** [comment]
sqlite3 test failures were fixed in master, so these are unrelated here

**Comment by adamruzicka** [comment]
[test]

**Comment by mmoll** [comment]
without getting rebased, tests will still fail like thay did before

**Comment by mmoll** [comment]
aw, please disregard my last comment, in plugins, as opposed to core, changes from PR are merged into the current development branch.

**Comment by adamruzicka** [comment]
You had me worried there for a moment :)

**Comment by adamruzicka** [comment]
Thanks @pondrejk, @mmoll !

**Pull request merged**
