### PR TITLE
fixes #12160 - fix test failures against 1.10

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
http://ci.theforeman.org/view/Plugins/job/test_plugin_pull_request/1548/

**Comment by stbenjam** [comment]
Green

**Comment by iNecas** [comment]
Get in in! :+1:

**Comment by jlsherrill** [comment]
APJ

**Comment by stbenjam** [comment]
Thanks!

**Pull request merged**
