### PR TITLE
Fixes #36096 - Add provider inputs to job wizard

### PR DESCRIPTION
**Pull request by MariaAga**
Adding them in the api response as part of the advanced inputs so that the ui will treat them as template inputs, and split them on submit from the advanced inputs.
Tested that they were actually added with ` TemplateInvocation.last.provider_input_values.first.value`

### CODE REVIEW

**Comment by MariaAga** [comment]
@adamruzicka are these normal ruby test failures?

**Comment by MariaAga** [comment]
rebased and the test failures are gone

**Review by adamruzicka — APPROVED** [review]
Seems to work well, ACK

**Comment by adamruzicka** [comment]
Thank you @MariaAga !

**Pull request merged**
