### PR TITLE
Fixes #35071 - Do not configure cleanup for REX jobs

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Setting cleanup interval for those actions won't be necessary once https://github.com/Katello/katello/pull/10096 gets in

**Comment by adamruzicka** [comment]
Can I do [test Redmine issues]?

**Comment by adamruzicka** [comment]
It was decided this should not be hardcoded and should be left to the user to configure. Closing

**Review by ofedoren — APPROVED** [review]
Thanks, @adamruzicka, let's get this in.

**Pull request merged**
