### PR TITLE
Fixes #31297 - Table pagination in react has extra space

### PR DESCRIPTION
**Pull request by MariaAga**
6px margin for pagination was removed from the table in: https://github.com/theforeman/foreman/pull/8133

### CODE REVIEW

**Comment by adamruzicka** [comment]
The foreman change + this one leads to a small visual artifact in job invocation details page. There seems to be doubled border between the end of the table and the pagination

image

**Comment by MariaAga** [comment]
Should be fixed, `viewType` is for css and added this border

**Comment by MariaAga** [comment]
theforeman/foreman#8133 was merged

**Review by ezr-ondrej — APPROVED** [review]
Thanks @MariaAga works nicely! :+1:

**Comment by ezr-ondrej** [comment]
@adamruzicka holding the merge as we should not release this with 2.3 and I don't know how we stand on release REX for `Foreman 2.3`

**Comment by ezr-ondrej** [comment]
As of offline discussion, this should not get in 2.3 thus merge should be safe :+1:

**Pull request merged**
