### PR TITLE
Fixes #21460 - s/FactoryGirl/FactoryBot/g + rubocop

### PR DESCRIPTION
**Pull request by adamruzicka**
FactoryGirl is now FactoryBot
factory_girl_rails is now factory_bot_rails

Requires theforeman/foreman#4935
Do not merge before Nov 1

### CODE REVIEW

**Comment by iNecas** [comment]
Should we update the deps on gemspec?

**Comment by ares** [comment]
@adamruzicka this needs rebase, today is the merge day :-)

**Comment by adamruzicka** [comment]
[test]

**Comment by adamruzicka** [comment]
Ok, so this now requires https://github.com/theforeman/foreman-tasks/pull/293, the tests are failing because of `FactoryGirl` being used in the latest release of `foreman-tasks`

**Comment by iNecas** [comment]
[test]

theforeman/foreman-tasks#293 merged and released

**Comment by adamruzicka** [comment]
The tests are green

**Comment by iNecas** [comment]
Thanks @adamruzicka

**Pull request merged**
