### PR TITLE
fixes #13317, #12538 - fix rubocop and mass assignment for foreman 1.11

### PR DESCRIPTION
**Pull request by stbenjam**
Based on the failures of http://ci.theforeman.org/job/test_plugin_pull_request/2133/, which tested the rubocop PR

### CODE REVIEW

**Comment by iNecas** [comment]
ACK, I'm just wondering why it was not failing on sqlite or mysql…

**Comment by stbenjam** [comment]
@iNecas Integration tests only run on postgresql

**Comment by iNecas** [comment]
@stbenjam that explains a lot :)

**Comment by iNecas** [comment]
Unfotrunately, it seems there is some issue with whitelisting the attribute this way (seems the original whitelisting is lost or something:/

**Comment by stbenjam** [comment]
Huh, in other cases attr_accessible adds to the existing set, other plugins do it too - I wonder what's gone wrong here :-\

**Comment by stbenjam** [comment]
It will pass against 1.11

```
09:07 | Dominic > you're running that on 1.10-stable which doesn't have any attr_accessible calls, so you're enabling protected attributes on the whole model 
```

**Comment by iNecas** [comment]
ah, ok

**Comment by stbenjam** [comment]
Against develop: http://ci.theforeman.org/view/Plugins/job/test_plugin_pull_request/2151/

**Comment by iNecas** [comment]
nice and green :)

**Comment by stbenjam** [comment]
Is that an ACK? :)

**Comment by stbenjam** [comment]
The job is also switched to develop a few minutes ago, as well

**Comment by iNecas** [comment]
ACKy ACK

**Pull request merged**
