### PR TITLE
Fixes #23016 - Fix setting refresh flag when retrieving output via API

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by iNecas** [comment]
@lpramuk mind tresting?

**Comment by iNecas** [comment]
I've tested and works well. Btw. requires https://github.com/theforeman/foreman-tasks/pull/326/commits, so we will need to wait until that's merged and bump dependency here.

**Comment by adamruzicka** [comment]
[test]

The dependency was merged

**Comment by iNecas** [comment]
Thanks. Test failures unrelated.

**Pull request merged**
