### PR TITLE
Fixes #33822 - job wizard add validation for repeat types

### PR DESCRIPTION
**Pull request by MariaAga**
Updates foreman-js to use `toggleAriaLabel`. another pr that updates it to the same version is https://github.com/theforeman/foreman_remote_execution/pull/663

### CODE REVIEW

**Comment by adamruzicka** [comment]
needs a rebase

**Comment by MariaAga** [comment]
Thanks, rebased

**Review by adamruzicka — APPROVED** [review]
Seems to work as expected, ACK

**Comment by adamruzicka** [comment]
Thank you @MariaAga !

**Pull request merged**
