### PR TITLE
Fixes #13142 - introduce advanced flag

### PR DESCRIPTION
**Pull request by ares**
RFC, I'm not sure if some icon next to link would help or maybe move schedule selection above inputs?

### CODE REVIEW

**Comment by ares** [comment]
invo1
invo2

**Comment by ohadlevy** [comment]
:+1: IMHO Schedule could also be advanced?

regarding icon - probably fa-angle-down or similar?

   -

**Comment by ares** [comment]
How about hiding `Type of query`, that's useful only for future and recurring scheduling. I'd prefer to keep scheduling visible since it's important feature and it's good for users to know about it. Also it doesn't take much space. And yeah, it looks better with icon 
advanced

**Comment by ares** [comment]
Latest version
full
there are too many radio buttons but advanced will be hidden most of the time I think

**Comment by stbenjam** [comment]
This is such a huge improvement!! :+1: :+1: 

I think the arrows should be different though - `fa-angle-right` when closed and `fa-angle-down` when open.  I think that's how most of these work? At least that's how @dLobatog's over in https://github.com/theforeman/foreman_remote_execution/pull/130 work for the template preview.

I don't much care just as long as we're consistent about it

**Comment by ares** [comment]
I changed the icons to be consistent, please take another look.

**Comment by stbenjam** [comment]
ackity ACK, works great!

**Comment by ares** [comment]
Thanks you, merging

**Pull request merged**
