### PR TITLE
Fixes #35494 - Replace Foreman to_bool with rails implementation

### PR DESCRIPTION
**Pull request by Dyrkon**
Replaced Foreman::Cast.to_bool with implementation from rails.

### CODE REVIEW

**Comment by adamruzicka** [comment]
Could we get a redmine issue for this?

**Comment by Dyrkon** [comment]
> Could we get a redmine issue for this?

Yes, I have added it.

**Review by adamruzicka — APPROVED** [review]
LGTM

**Comment by adamruzicka** [comment]
Thank you @Dyrkon !

**Pull request merged**
