### PR TITLE
Fixes #27325 - Enable autocomplete for job description

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Erm, issue number off by one

**Comment by ares** [comment]
works like a charm, jenkins says 404, let's retry [test foreman_remote_execution]

**Comment by adamruzicka** [comment]
Tests are green-ish

**Comment by ares** [comment]
yeah, audit failures unrelated, just waiting for 2.6 to finish and good to merge

**Comment by ares** [comment]
Thanks @adamruzicka, failures are unrelated. Merging!

**Pull request merged**
