### PR TITLE
Hook rake tests on test:plugins

### PR DESCRIPTION
**Pull request by lzap**
See https://github.com/theforeman/foreman/pull/3666

### CODE REVIEW

**Comment by lzap** [comment]
Do you guys insist on it?

**Comment by stbenjam** [comment]
@lzap For anything going into a release, yes.  Dev tasks like this I personally don't, not sure what others think

**Comment by lzap** [comment]
Done

**Comment by iNecas** [comment]
[test]

**Comment by stbenjam** [comment]
Will fail until foreman PR is merged I think

**Comment by iNecas** [comment]
Oh, I have not realized that

**Comment by adamruzicka** [comment]
The foreman PR was closed so I'll close this one as well. If you want to reopen it, feel free to

**Pull request closed without merging**
