### PR TITLE
Fixes #32439 - Add error state to job wizard

### PR DESCRIPTION
**Pull request by MariaAga**
When one of the api calls in job wizard fails there is now an error shown.
Currently there are only api calls to get  the categories list and templates list
Screenshot from 2021-05-05 12-40-34

### CODE REVIEW

**Review by stejskalleos — CHANGES_REQUESTED** [review]
Hi,
just two nitpicks, otherwise works as described!

**Comment by MariaAga** [comment]
Fixed! thanks!

**Review by stejskalleos — APPROVED** [review]

**Review by adamruzicka — APPROVED** [review]
Works as expected, ACK

**Comment by adamruzicka** [comment]
Thank you @MariaAga & @stejskalleos !

**Pull request merged**
