### PR TITLE
Fixes #31109 - use non-interactive mode

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by adamruzicka** [comment]
What will happen when you try to install a package which requires interactive response? Will it fail? Will it just accept whatever prompt would come up?

**Comment by sbernhard** [comment]
apt-get will  use the default selection.

**Review by adamruzicka — APPROVED** [review]
Makes sense, ACK

**Comment by adamruzicka** [comment]
Thank you @sbernhard !

**Pull request merged**
