### PR TITLE
fixes #13331 - drop 1.10 support and bump version to 0.3.0

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
The right commit message would help, I really shouldn't release things on a Friday :grin:

I think this is all we need to do to drop 1.10, right?

**Comment by iNecas** [comment]
Yes, while dropping the version, we can remove some conditions, see `grep -r Rails::VERSION .` for the parts that can be updated

**Comment by dLobatog** [comment]
Two questions arise:

1) Why? Are there any non-backwards compatible changes other than the patternfly icons thing?
2) I don't know what kind of versioning schema does this project follow. Minor versions are supposed to be fixes & small features compatible with older versions, so this ought to be 1.0 instead? That's assuming this follows http://semver.org/ as other plugins/core/proxy/etc

**Comment by stbenjam** [comment]
> 1) Why? Are there any non-backwards compatible changes other than the patternfly icons thing?

https://github.com/theforeman/foreman_remote_execution/pull/72 which is a nice usability improvement.   Do note we have 0.2.0 which is compatible with 1.10, which was just released with all the new features that were demo'd.

**Comment by iNecas** [comment]
@dLobatog yes, we try to follow the semver, but note http://semver.org/#spec-item-4 - there is a special case for 0-starting releases. We might switch to first API-stable release, but I would still give it some time until we gain more experience with the API and how it fits users.

**Comment by stbenjam** [comment]
Updated to remove the Rails 3 bits

**Comment by ares** [comment]
also please drop https://github.com/theforeman/foreman_remote_execution/blob/master/app/assets/stylesheets/job_invocations.css.scss#L24 since https://github.com/theforeman/foreman/blob/develop/app/assets/stylesheets/status-colors.scss

otherwise looks good to me and works fine

**Comment by stbenjam** [comment]
Done

**Comment by ares** [comment]
Thanks @stbenjam, merging!

**Pull request merged**
