### PR TITLE
Fixes #37213 - Add missing ouia-ids

### PR DESCRIPTION
**Pull request by MariaAga**
It was really optimistic to assume in https://github.com/theforeman/foreman_remote_execution/pull/821 that we didnt need to fix anything...
This pr actually makes it so REX will use the rule.

### CODE REVIEW

**Review by kmalyjur — APPROVED** [review]
Works nicely, all the ouia-ids added, thank you

(It could maybe also fix this warning? However, I get that this PR is about something else.)
image

**Comment by MariaAga** [comment]
> (It could maybe also fix this warning? However, I get that this PR is about something else.)

Lets do that in a seperate one

**Comment by MariaAga** [comment]
@lhellebr does this fix the issue? (https://bugzilla.redhat.com/show_bug.cgi?id=2265127)

**Comment by lhellebr** [comment]
Yes, that BZ is fixed when I apply this PR to Stream. `data-ouia-component-id` is now statically `hosts`.

**Review by adamruzicka — APPROVED** [review]

**Comment by adamruzicka** [comment]
Thank you @MariaAga , @kmalyjur & @lhellebr !

**Pull request merged**
