### PR TITLE
Fixes #21804 - remove doc directory

### PR DESCRIPTION
**Pull request by iNecas**
We have the documentation on theforeman.org: no need to have anything
in doc here.

### CODE REVIEW

**Comment by adamruzicka** [comment]
> image

Wow, that's a lot.

ACK anyway, it probably doesn't make sense to even wait for the tests to finish.

**Comment by iNecas** [comment]
Tests are green

**Comment by adamruzicka** [comment]
Oh, right!

**Comment by adamruzicka** [comment]
Thanks @iNecas !

**Pull request merged**
