### PR TITLE
Fixes #20391 - Fix permissions in tests

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Tests are running here https://github.com/theforeman/foreman_remote_execution/pull/265

**Comment by ares** [comment]
the question is, do we still need separate execute permission now? with the change in core, the permission check is now performed also before the job invocation is created (probably a separate thing)

**Comment by iNecas** [comment]
Tests are running where? :)

**Comment by adamruzicka** [comment]
Ermm, here http://ci.theforeman.org/job/test_plugin_pull_request/3942/

**Comment by iNecas** [comment]
Thanks @adamruzicka, @ares could you file an issue for that?

**Comment by ares** [comment]
sure, opened as http://projects.theforeman.org/issues/20455

**Comment by iNecas** [comment]
Thanks. The issues description also helped me to understand what's the request itself :)

**Pull request merged**
