### PR TITLE
Fixes #32218 - Host Registration - New form

### PR DESCRIPTION
**Pull request by stejskalleos**
For: https://github.com/theforeman/foreman/pull/8419

No changes in behavior, just refactoring to React & PF4 components.

### CODE REVIEW

**Review by laviro — APPROVED** [review]
Thanks @stejskalleos !! Tested with the core PR and looks great to me :)

**Comment by adamruzicka** [comment]
Could you bump required foreman version?

**Comment by ares** [comment]
there's a conflict now

**Comment by stejskalleos** [comment]
Rebased.

**Review by adamruzicka — APPROVED** [review]
Works nicely, ACK

**Comment by adamruzicka** [comment]
Thank you @stejskalleos !

**Pull request merged**
