### PR TITLE
Fixes #24930 - Make output fail with 404 when job is missing

### PR DESCRIPTION
**Pull request by adamruzicka**
Before this commit we failed with 500: Internal Server Error

### CODE REVIEW

**Comment by rplevka** [comment]
tested this downstream:
```
# hammer job-invocation output --id=58 --host stub-999
Resource job_invocation not found by id ''
```

```
2018-09-13T09:09:18 [I|app|ecc06] Processing by Api::V2::JobInvocationsController#output as JSON
2018-09-13T09:09:18 [I|app|ecc06]   Parameters: {"since"=>nil, "apiv"=>"v2", "job_invocation_id"=>"58", "host_id"=>"1017", "job_invocation"=>{}}
2018-09-13T09:09:18 [I|app|ecc06] Current user: foreman_admin (administrator)
2018-09-13T09:09:18 [I|app|ecc06] Authorized user admin(Admin User)
2018-09-13T09:09:18 [I|app|ecc06] Current user: admin (administrator)
2018-09-13T09:09:18 [I|app|ecc06]   Rendering api/v2/errors/not_found.json.rabl within api/v2/layouts/error_layout
2018-09-13T09:09:18 [I|app|ecc06]   Rendered api/v2/errors/not_found.json.rabl within api/v2/layouts/error_layout (0.7ms)
2018-09-13T09:09:18 [I|app|ecc06] Filter chain halted as :find_required_nested_object rendered or redirected
2018-09-13T09:09:18 [I|app|ecc06] Completed 404 Not Found in 36ms (Views: 1.4ms | ActiveRecord: 18.0ms)
```

the return code is correct now, however the hammer output does not show the id in the message. Perhaps this is related to the hammer-cli

**Comment by rplevka** [comment]
ok, this now works as well, thanks @adamruzicka !

```
[root@intel-lizardhead-02 v2]# hammer job-invocation output --id=58 --host stub-999
Job invocation not found by id '58'
```

**Comment by iNecas** [comment]
Test failures unrelated

**Comment by iNecas** [comment]
Thanks @adamruzicka

**Pull request merged**
