### PR TITLE
Fixes #34362 - fix 'host detail' button to include the new page

### PR DESCRIPTION
**Pull request by amirfefer**

### CODE REVIEW

**Review by ezr-ondrej — COMMENTED** [review]
Works well, but could we also fix it in:
https://github.com/theforeman/foreman_remote_execution/blob/a98967eef757513bbbc7df8c116d892585e13d8e/app/views/template_invocations/show.html.erb#L33

and

https://github.com/theforeman/foreman_remote_execution/blob/972e8536f602068445527b3813609fa543694851/app/views/job_invocations/_preview_hosts_list.html.erb#L10

**Review by ares — APPROVED** [review]
Works great, thanks @amirfefer, merging

**Comment by ares** [comment]
oh sorry, I had it open and github didn't show me the update, @amirfefer could you pelase address @ezr-ondrej's comment in a separate PR? Sorry for the mess I only saw that after the merge.

**Comment by amirfefer** [comment]
https://github.com/theforeman/foreman_remote_execution/pull/690

**Comment by ezr-ondrej** [comment]
> Sorry for the mess I only saw that after the merge.

No worries, I hoped to have that in a single commit for future reference, but we have the Redmine ticket for that :)

**Pull request merged**
