### PR TITLE
Fixes #21358 - cancelled state for delayed jobs

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by iNecas** [comment]
Tested and works well. Waiting for the jenkins + https://github.com/Dynflow/dynflow/pull/265 to be released so that we can bump a dependency on dynflow

**Comment by bkearney** [comment]
@adamruzicka Dmitri is no longer working on the project. Can this be adopted by someone still in the community?

**Comment by adamruzicka** [comment]
We have this on our team's backlog

**Comment by adamruzicka** [comment]
Closing this in favor of https://github.com/theforeman/foreman_remote_execution/pull/482

**Pull request closed without merging**
