### PR TITLE
WIP Fixing tests

### PR DESCRIPTION
**Pull request by ares**
This should be compatible with Foreman 1.11 as well, so I'm not setting 1.12 flag.

### CODE REVIEW

**Comment by stbenjam** [comment]
What do you think about adding `validates_lengths_from_database` to our models, too?

**Comment by stbenjam** [comment]
And if you want to include https://github.com/theforeman/foreman_remote_execution/pull/175 it'll make tests green, since it's really part of the same issue

**Comment by ares** [comment]
yesh, seems #175 is going to be much bigger PR, we can combine these too

**Comment by ares** [comment]
All tests should run now except one unit and two functionals which are fixed by https://github.com/theforeman/foreman-tasks/pull/183

**Comment by ares** [comment]
let's see what fails now [test]

**Comment by stbenjam** [comment]
@ares For the problem where rake tests fail but tests are green, @domcleal proposed a solution in https://github.com/theforeman/foreman_remote_execution/pull/175#issuecomment-214745632 - do you want to include that change here, or want me to open a separate PR?

**Comment by stbenjam** [comment]
Build is unstable now, manual test here: http://ci.theforeman.org/view/Plugins/job/test_plugin_pull_request/2547/

**Comment by ares** [comment]
@stbenjam I includeed rake task changes here, running new build http://ci.theforeman.org/view/Plugins/job/test_plugin_pull_request/2550/

**Comment by ares** [comment]
This PR addresses following issues so far: 14842 14752 14751

**Comment by ares** [comment]
Green run - http://ci.theforeman.org/view/Plugins/job/test_plugin_pull_request/2551/

**Comment by iNecas** [comment]
:shipit: :)

**Comment by stbenjam** [comment]
I don't mind if you want to take my commit and squash it into one

**Comment by stbenjam** [comment]
Oh, nevermind :)

**Comment by ares** [comment]
sorry too late :-)

**Pull request merged**
