### PR TITLE
Fixes #37557 - change job wizard width

### PR DESCRIPTION
**Pull request by MariaAga**
so users will have more space to type in

### CODE REVIEW

**Comment by pondrejk** [comment]
Hello, I'm in for the proposed solution but it seems that the search field for hosts is not affected and maintains the narrow width

image

**Comment by MariaAga** [comment]
@pondrejk can you inspect ` #host-selection` to make sure that the pr is applied and its not limited to 500px?
image

**Comment by MariaAga** [comment]
Should be good now

**Review by adamruzicka — APPROVED** [review]
LGTM

**Comment by adamruzicka** [comment]
Thank you @MariaAga & @pondrejk !

**Pull request merged**
