### PR TITLE
Fixes #18003 - redirect STDIN

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Works as expected, let's wait for Mr. Jenkins' approval

**Comment by adamruzicka** [comment]
[test]

**Comment by adamruzicka** [comment]
[test]

**Comment by ares** [comment]
Now failed only on sqlite3 + Ruby 2.0.0.

**Comment by ares** [comment]
Hopefully not caused by this patch
```
ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds
```

**Comment by adamruzicka** [comment]
It seems all the REX tests are now failing with this error on ruby 2.0 with sqlite3. I even managed to reproduce it on my machine, but I haven't found the cause (and fix for it) yet.

**Comment by iNecas** [comment]
[test] - the fixes seem to be realted by foreman-tasks in core

**Comment by iNecas** [comment]
I'm not expecting anything new from the jenkins. Thanks @ares and @adamruzicka

**Pull request merged**
