### PR TITLE
Fixes #14560 - Reuse foreman's core documentation helper.

### PR DESCRIPTION
**Pull request by ShimShtein**
Waits for https://github.com/theforeman/foreman/pull/3407.

### CODE REVIEW

**Comment by stbenjam** [comment]
@ShimShtein  Is the foreman PR targeted for 1.12?

**Comment by ShimShtein** [comment]
https://github.com/theforeman/foreman/pull/3407 merged. This one can be merged too.

**Comment by ShimShtein** [comment]
I think it is: [redmine](http://projects.theforeman.org/issues/14559#note-4)

**Comment by stbenjam** [comment]
Got it, thanks. We're not dropping 1.11 yet, but soon.  Will merge then.  Thanks @ShimShtein !

**Comment by ShimShtein** [comment]
Added condition to support 1.11 core.

**Comment by stbenjam** [comment]
@ShimShtein Hey sorry for the back and forth on this, but we'll be dropping 1.11 entirely, so you can remove the version check here

**Comment by ShimShtein** [comment]
Removed the version check. Now the code is much cleaner.

**Comment by stbenjam** [comment]
Transient [test] failure

**Comment by ShimShtein** [comment]
Failed on `HostJSTest::NIC modal window::adding interfaces.test_0004_selecting domain updates subnet list`. Seems unrelated.

**Comment by ares** [comment]
[test]

**Comment by stbenjam** [comment]
Thanks @ShimShtein !

**Pull request merged**
