### PR TITLE
Fix the tags check for the release gem action

### PR DESCRIPTION
**Pull request by sbernhard**
See https://github.com/theforeman/actions/pull/50

### CODE REVIEW

**Comment by adamruzicka** [comment]
This never really worked at all, could we drop it instead?

**Comment by sbernhard** [comment]
You mean, to drop the whole github action? 
Actually, for foreman_acd it works pretty good.

**Comment by adamruzicka** [comment]
> You mean, to drop the whole github action?

Yes

>  Actually, for foreman_acd it works pretty good.

Well, this one does not and it doesn't fit into the way how I release things anyway.

**Comment by sbernhard** [comment]
Well, if you have "your way" to release the plugin, feel free to remove it again

**Review by adamruzicka — APPROVED** [review]

**Comment by adamruzicka** [comment]
Alright, I'll give it another chance

**Pull request merged**
