### PR TITLE
Fixes #15311 allow large inputs

### PR DESCRIPTION
**Pull request by iNecas**
Addresses comments in https://github.com/theforeman/foreman_remote_execution/pull/205

### CODE REVIEW

**Comment by stbenjam** [comment]
This looks reasonable to me, but tests are failing on master: http://ci.theforeman.org/job/test_plugin_matrix/2026/

**Comment by adamruzicka** [comment]
Works as expected, but can mess up the UI and flow out of the screen.
job invocation detail overflow

On the job invocation index page we should truncate the descriptions the same way we do it on tasks index
job invocation index overflow

**Comment by iNecas** [comment]
I've added some truncation in place to make sure we don't go too far, @adamruzicka or @stbenjam, might re-review?

**Comment by adamruzicka** [comment]
Looks good and works as expected, ACK

**Comment by iNecas** [comment]
Thanks folks!

**Pull request merged**
