### PR TITLE
Fixes #13143 - move scheduling back to invocation form

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
I improved styling a bit as well.
scheduling
scheduling2

**Comment by stbenjam** [comment]
Looks different for me when I checkout this branch:

foo

**Comment by ares** [comment]
yeah, sorry, I pushed it too soon, please test with https://github.com/theforeman/foreman-tasks/pull/167

**Comment by ares** [comment]
[test] (intermittent)

**Comment by iNecas** [comment]
My patience with intermittent issues is over, tested and works well. ACK from my side (and I don't insist on waiting for jenkins)

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
needs rebase

**Comment by stbenjam** [comment]
ACK, tested, looks much better :+1:

**Comment by ares** [comment]
thanks, merging

**Pull request merged**
