### PR TITLE
Fixes #22688 - Use UUID column type for storing task UUIDs

### PR DESCRIPTION
**Pull request by adamruzicka**
Required after https://github.com/theforeman/foreman-tasks/pull/315 goes in

### CODE REVIEW

**Comment by iNecas** [comment]
Test failures related

**Comment by adamruzicka** [comment]
To be precise, this is required for REX to work with tasks with UUID column type and at the same time it requires tasks with UUID column type to work at all Waiting for new foreman-tasks release

**Comment by iNecas** [comment]
foreman-tasks-0.12.0 just released, please update the dependency on it here

**Comment by adamruzicka** [comment]
Tests running here http://ci.theforeman.org/job/test_plugin_pull_request/4748/

**Comment by iNecas** [comment]
Seems even there were some intermittent issues, starting again in http://ci.theforeman.org/job/test_plugin_pull_request/4752/

**Comment by iNecas** [comment]
The test failures unrelated. Merging, as otherwise rex is not compatible with tasks

**Pull request merged**
