### PR TITLE
Fixes #20285 - Resolve static targeting only once when recurring

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Test failures seem unrelated

**Comment by iNecas** [comment]
It doesn't seem to work for me: when i scheduled cronline of `* * * * *`, with this patch, only the first invocation is scheduled. Without this patch, the recurring logic works (new instance are being scheduled)

**Comment by iNecas** [comment]
```
2018-09-26T13:59:11 [E|bac|] Validation failed: Targeting is invalid (ActiveRecord::RecordInvalid)
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/validations.rb:80:in `raise_validation_error'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/validations.rb:52:in `save!'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:315:in `block in save!'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:315:in `save!'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/suppressor.rb:48:in `save!'
 | /home/inecas/Projects/ws/foreman-rex/foreman_remote_execution/app/models/job_invocation.rb:147:in `tap'
 | /home/inecas/Projects/ws/foreman-rex/foreman_remote_execution/app/models/job_invocation.rb:147:in `deep_clone!'
 | /home/inecas/Projects/ws/foreman-rex/foreman_remote_execution/app/lib/actions/middleware/bind_job_invocation.rb:9:in `delay'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:18:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/foreman-tasks/app/lib/actions/middleware/recurring_logic.rb:11:in `delay'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:18:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:27:in `delay'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:18:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:27:in `delay'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:18:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/foreman-tasks/app/lib/actions/middleware/keep_current_user.rb:5:in `delay'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:18:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:27:in `delay'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/world.rb:30:in `execute'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/action.rb:303:in `block in execute_delay'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/action.rb:451:in `block in with_error_handling'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/action.rb:451:in `catch'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/action.rb:451:in `with_error_handling'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/action.rb:302:in `execute_delay'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan/steps/plan_step.rb:39:in `delay'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan.rb:257:in `delay'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/world.rb:193:in `delay_with_caller'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/world.rb:187:in `delay'
 | /home/inecas/Projects/ws/foreman-rex/foreman-tasks/lib/foreman_tasks.rb:53:in `delay'
 | /home/inecas/Projects/ws/foreman-rex/foreman-tasks/app/models/foreman_tasks/recurring_logic.rb:64:in `trigger_repeat_after'
 | /home/inecas/Projects/ws/foreman-rex/foreman-tasks/app/lib/actions/recurring_action.rb:16:in `trigger_repeat'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan/hooks.rb:68:in `block (2 levels) in run'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan/hooks.rb:66:in `each'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan/hooks.rb:66:in `block in run'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/executors.rb:12:in `run_user_code'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan/hooks.rb:65:in `run'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan.rb:153:in `block (2 levels) in run_hooks'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:18:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:55:in `hook'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:18:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:55:in `hook'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:18:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:55:in `hook'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:18:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:55:in `hook'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:18:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:55:in `hook'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:18:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/foreman-tasks/app/lib/actions/middleware/keep_current_user.rb:24:in `block in hook'
 | /home/inecas/Projects/ws/foreman-rex/foreman-tasks/app/lib/actions/middleware/keep_current_user.rb:43:in `restore_curent_user'
 | /home/inecas/Projects/ws/foreman-rex/foreman-tasks/app/lib/actions/middleware/keep_current_user.rb:24:in `hook'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:18:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware.rb:55:in `hook'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/middleware/world.rb:30:in `execute'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan.rb:152:in `block in run_hooks'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan.rb:151:in `each'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan.rb:151:in `run_hooks'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan.rb:140:in `block in update_state'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan.rb:140:in `each'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan.rb:140:in `update_state'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/execution_plan.rb:300:in `plan'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/delayed_plan.rb:26:in `plan'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/delayed_executors/abstract_core.rb:61:in `block (3 levels) in process'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/executors.rb:12:in `run_user_code'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/delayed_executors/abstract_core.rb:60:in `block (2 levels) in process'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/delayed_executors/abstract_core.rb:39:in `with_error_handling'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/delayed_executors/abstract_core.rb:51:in `block in process'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/delayed_executors/abstract_core.rb:48:in `each'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/delayed_executors/abstract_core.rb:48:in `process'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/delayed_executors/polling.rb:26:in `check_delayed_plans'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/actor.rb:6:in `on_message'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/context.rb:46:in `on_envelope'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/executes_context.rb:7:in `on_envelope'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/inecas/Projects/ws/foreman-rex/dynflow/lib/dynflow/actor.rb:26:in `on_envelope'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/awaits.rb:15:in `on_envelope'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/sets_results.rb:14:in `on_envelope'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/buffer.rb:38:in `process_envelope'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/buffer.rb:31:in `process_envelopes?'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/buffer.rb:20:in `on_envelope'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/termination.rb:55:in `on_envelope'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/removes_child.rb:10:in `on_envelope'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/behaviour/sets_results.rb:14:in `on_envelope'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/core.rb:161:in `process_envelope'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/core.rb:95:in `block in on_envelope'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/core.rb:118:in `block (2 levels) in schedule_execution'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-edge-0.2.4/lib/concurrent/actor/core.rb:115:in `block in schedule_execution'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/serialized_execution.rb:18:in `call'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/serialized_execution.rb:96:in `work'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/serialized_execution.rb:77:in `block in call_job'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
 | /home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2018-09-26T13:59:11 [E|dyn|] Failed to run hook 'trigger_repeat' for action 'Actions::RemoteExecution::RunHostsJob'

```

**Comment by adamruzicka** [comment]
[test foreman_remote_execution]

**Comment by iNecas** [comment]
Tested and works well. Thanks @adamruzicka

**Pull request merged**
