### PR TITLE
Fixes #17953 - extend core roles with permissions

### PR DESCRIPTION
**Pull request by ares**
Please consider merging this before another release. This is new plugin DSL introduced in 1.15 that adds all permissions to Manager role and all view_* permissions to Viewer core roles.

### CODE REVIEW

**Comment by adamruzicka** [comment]
[test]

**Comment by adamruzicka** [comment]
Looks good to me, setting to 'Waiting on contributor' untill the test issues are resolved

**Comment by lzap** [comment]
Core merged [test]

**Comment by lzap** [comment]
Can you guys trigger [test] I am not in right group here.

**Comment by adamruzicka** [comment]
[test]

**Comment by lzap** [comment]
It is green, *sigh*.

**Comment by adamruzicka** [comment]
Thanks @ares

**Pull request merged**
