### PR TITLE
Fixes #14019 - Use template name as default description template

### PR DESCRIPTION
**Pull request by adamruzicka**
Originally we used job_category.

### CODE REVIEW

**Comment by iNecas** [comment]
Test failures related

**Comment by adamruzicka** [comment]
[test]

**Comment by iNecas** [comment]
@adamruzicka you probably meant [test foreman_remote_execution] - after the changes in the pr scanner, the previous way doesn't work anymore.

**Comment by adamruzicka** [comment]
Right, I wasn't sure which way is the right way now. Anyway, thanks for triggering the tests, they're green now

**Comment by iNecas** [comment]
Thanks @adamruzicka

**Pull request merged**
