### PR TITLE
Refs #34396 - reflect the report name change

### PR DESCRIPTION
**Pull request by ares**
This will be required, once the https://github.com/theforeman/foreman/pull/9093 is merged.

### CODE REVIEW

**Review by adamruzicka — APPROVED** [review]
This is fine, putting on hold until the change in foreman is merged

**Comment by adamruzicka** [comment]
This relies on something which will appear in Foreman 3.4. Let's put this on hold for now so I won't have to make releasing easier

**Comment by adamruzicka** [comment]
Ah, change of plans, the change in core broke our tests. Could you rebase please and address the test failures caused by the template living in a different location?

**Comment by ares** [comment]
Done, min Foreman version bumped to 3.4, I'm not touching the plugin version.

**Review by adamruzicka — CHANGES_REQUESTED** [review]
:police_officer:

**Comment by adamruzicka** [comment]
The test failure should have been resolved by https://github.com/theforeman/foreman_remote_execution/pull/723 :thinking:

**Review by ofedoren — APPROVED** [review]

**Pull request merged**
