### PR TITLE
Fixes #36308 - Remove * for non required fields

### PR DESCRIPTION
**Pull request by girijaasoni**
This pr is in reference to foreman pr: https://github.com/theforeman/foreman/pull/9686

### CODE REVIEW

**Comment by girijaasoni** [comment]
@MariaAga could you please review it

**Review by MariaAga — APPROVED** [review]
Works as expected

**Review by Ron-Lavi — APPROVED** [review]

**Review by adamruzicka — COMMENTED** [review]
Should this also drop isRequired from "REX pull mode", even though the issue doesn't state that explicitly?

**Review by stejskalleos — CHANGES_REQUESTED** [review]
`FormSelect` still has `isRequired`

**Comment by girijaasoni** [comment]
> `FormSelect` still has `isRequired`

updated

**Review by Ron-Lavi — APPROVED** [review]
Nice catch @adamruzicka, funny that it worked well even without the other `isRequired`
looks good to me now, thanks @girijaasoni !

**Comment by adamruzicka** [comment]
Thank you @girijaasoni !

**Pull request merged**
