### PR TITLE
Fixes #22483 - override host_param instead of host_params

### PR DESCRIPTION
**Pull request by ares**
to reproduce, try to preview remote_execution_ssh_keys snippet

### CODE REVIEW

**Comment by iNecas** [comment]
Other places also need updating, otherwise I guess this would not work https://github.com/theforeman/foreman_remote_execution/blob/9a8264b4a9e26c44dddb00934898e8a9529629cc/app/models/ssh_execution_provider.rb#L21 and https://github.com/theforeman/foreman_remote_execution/blob/9a8264b4a9e26c44dddb00934898e8a9529629cc/app/models/ssh_execution_provider.rb#L21?

Alternatively, we could override the `host_params_hash` to include the values.

**Comment by iNecas** [comment]
Btw. using the `host_param` method from other places will also have quite nice performance benefits, as we will not need to evaluate the `SmartVariables`

**Comment by adamruzicka** [comment]
[test]

**Comment by iNecas** [comment]
This needs to be re-worked, I talked to @ares and we will re-open the re-worked PR, as @ares is out of capacity these days.

**Comment by iNecas** [comment]
Closing in favor of https://github.com/theforeman/foreman_remote_execution/pull/349

**Pull request closed without merging**
