### PR TITLE
Fixes #35721 - reset to default button to job wizard fields

### PR DESCRIPTION
**Pull request by MariaAga**
Adds a button next to every field that can have a default value to reset the field to that value.
Will show button only for fields that have a default value
example screenshot:
Screenshot from 2022-11-04 20-03-34

### CODE REVIEW

**Review by adamruzicka — CHANGES_REQUESTED** [review]
In general it seems to work well.

The only place where it doesn't seem to work if for inputs of type search where clicking the reset button does nothing at all.

Another thing I noticed is that inputs of type resource cannot be used with the wizard at all, the wizard crashes at the review step. That doesn't seem to be caused by this PR so I filed https://projects.theforeman.org/issues/35725 to track it.

**Comment by MariaAga** [comment]
Fixed the search inputs

**Review by adamruzicka — APPROVED** [review]
Nothing to add here, well done

**Comment by adamruzicka** [comment]
Thank you @MariaAga !

**Pull request merged**
