### PR TITLE
refs #24130 - pass source to template scope

### PR DESCRIPTION
**Pull request by timogoebel**
After https://github.com/theforeman/foreman/commit/b58439fabbeac20b68902021fed366725c26dc92 was merged, we should also pass the source to the scope so snippets still work correctly.

### CODE REVIEW

**Comment by iNecas** [comment]
What's the reproducer for the issue? It seems I can use a snippet in job templates even without this patch.

**Comment by timogoebel** [comment]
> What's the reproducer for the issue? It seems I can use a snippet in job templates even without this patch.

@iNecas: This will only break if the snippets are defined by another source. So right now, this should just be a cosmetic change.

**Comment by iNecas** [comment]
When trying to preview the template with this patch, I'm getting `Warning! Problem with previewing the template: error during rendering: unknown keyword: source. Note that you must save template input changes before you try to preview it.`

**Comment by timogoebel** [comment]
Are you on the latest core develop? The kwarg should be defined, see https://github.com/theforeman/foreman/blob/b58439fabbeac20b68902021fed366725c26dc92/lib/foreman/renderer.rb#L35.
Also tests seem to pass on jenkins.

**Comment by timogoebel** [comment]
@iNecas: Thanks. Rebased.

**Comment by iNecas** [comment]
Thanks @timogoebel

**Pull request merged**
