### PR TITLE
Initial support for triggering commands on smart proxy

### PR DESCRIPTION
**Pull request by iNecas**
TODO:
- [x] tests

Requires:

* on server side:
  * https://github.com/theforeman/foreman-tasks/pull/125 on server

* on smart proxy side
  * https://github.com/theforeman/smart_proxy_dynflow/pull/1
  * https://github.com/theforeman/smart_proxy_remote_execution_ssh/pull/1

There is still work to be done (etc. better edge case handling), but I would preffer
filing sub-tasks for that and finding the minimal viable patch to get in now.

### CODE REVIEW

**Comment by ares** [comment]
LGTM so far, what's the plan to keep track of tasks for a particular invocation? locks somehow? I guess we'll need a way to cancel the whole batch...

**Comment by iNecas** [comment]
The bulk actions is the thing that should be usable for that https://github.com/theforeman/foreman-tasks/blob/master/app/lib/actions/bulk_action.rb: this is another task that tracks the sub-tasks, and should allows distributing the cancel events to handle situations like that.

**Comment by ares** [comment]
sounds good

**Comment by iNecas** [comment]
@ares I've rebased the code and connected the actions with job invocation, so now, after you hit 'run job', the task will be created, rendering and passing the commands to the proxy, showing the progress in the meantime.

For testing, you might need to re-save the templates you use, as I needed to use 'Ssh', instead of 'ssh' in the provider name to match it with the 'Ssh' proxy feature

**Comment by iNecas** [comment]
I've merged invocation details updates by @ares and added ability to cancel the tasks, requires latest updates from https://github.com/Dynflow/dynflow/pull/162 and https://github.com/theforeman/foreman-tasks/pull/125

**Comment by ares** [comment]
ACK pending fixed tests, thanks for answers

**Comment by ares** [comment]
:+1: except two nits

**Comment by iNecas** [comment]
dynflow-0.8.3, foreman-tasks-0.7.3, smart_proxy_dynflow-0.0.1, smart_proxy_remote_execution_ssh-0.0.1 released, waiting for https://github.com/iNecas/foreman_remote_execution/pull/2 and some tests for RunHostJob

**Pull request merged**
