### PR TITLE
Fixes #35715 - Add time-to-pickup field to rex wizard

### PR DESCRIPTION
**Pull request by MariaAga**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Needs a rebase

**Comment by adamruzicka** [comment]
Apart from the needed rebase it seems to work well.

**Comment by MariaAga** [comment]
Rebased, thanks

**Review by adamruzicka — APPROVED** [review]
Works like a charm

**Comment by adamruzicka** [comment]
Thank you @MariaAga !

**Pull request merged**
