### PR TITLE
Disable TravisCI in favor of GH actions

### PR DESCRIPTION
**Pull request by ezr-ondrej**

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
I've disabled travis in it's UI, after agreement on this, we could maybe get it removed from there?

**Comment by ezr-ondrej** [comment]
Also, who can disable the :guide_dog: who's not doing anything, just woofing now :thinking:

**Comment by adamruzicka** [comment]
No more woofing from this point onwards

**Comment by adamruzicka** [comment]
Thank you @ezr-ondrej !

**Pull request merged**
