### PR TITLE
Make API controller test consistent

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
http://ci.theforeman.org/view/Plugins/job/test_plugin_pull_request/1013/

**Comment by jlsherrill** [comment]
Is this still needed if we start testing against 1.9?

**Comment by stbenjam** [comment]
It's needed eventually, and its compatible with 1.9.

I botched the parameters on the one above, running again here http://ci.theforeman.org/view/Plugins/job/test_plugin_pull_request/1014/

**Comment by jlsherrill** [comment]
ACK

**Comment by stbenjam** [comment]
We will actually need another PR once we switch to develop, as develop will required `assert :created` on the create tests but at least this made the test consistent in terms of quotes and assertions.

**Comment by stbenjam** [comment]
Thanks @jlsherrill

**Pull request merged**
