### PR TITLE
Remote execution shutdown command

### PR DESCRIPTION
**Pull request by anandkumaragrawal**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Is `/sbin/shutdown` available on *all* platforms? The issue mentions RHEL variants only.

**Comment by adamruzicka** [comment]
Also could you please rebase it so it is just a single commit?

**Comment by adamruzicka** [comment]
How about instead of hardcoding the path to `/usr/sbin/shutdown`, we append `/usr/sbin` to the end of `PATH` env variable and leave the rest untouched?

**Comment by adamruzicka** [comment]
@anandkumaragrawal ping

**Comment by anandkumaragrawal** [comment]
> @anandkumaragrawal ping

Hey @adamruzicka  pong,

Your suggestion looks good. However, I am occupied. Would you like to change it and fix that.

Regards,
Anand

**Comment by adamruzicka** [comment]
Ok, closing in favor of https://github.com/theforeman/foreman_remote_execution/pull/640. Thank you @anandkumaragrawal

**Pull request closed without merging**
