### PR TITLE
Fixes #18515 - Show scheduling info on job invocation overview tab

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Now requires https://github.com/theforeman/foreman-tasks/pull/237

**Comment by iNecas** [comment]
@adamruzicka would you mind addressing https://bugzilla.redhat.com/show_bug.cgi?id=1426773 here as well?

**Comment by adamruzicka** [comment]
Not at all, I'll see what can be done about it.

**Comment by adamruzicka** [comment]
How about this?

Screenshot

**Comment by adamruzicka** [comment]
CC @rohoover

**Comment by Rohoover** [comment]
@adamruzicka 

Sorry for the delayed response. My main issue with this page, is that what is displayed is not in the same order of how it was inputed. Also - the status message in the right hand corner is sort of lost in a void. I can work for a visual solution if desired.

**Comment by iNecas** [comment]
Thanks @adamruzicka !

**Pull request merged**
