### PR TITLE
Fixes #36457, #36458 - wizard tooltip text and show Time to pickup in job details

### PR DESCRIPTION
**Pull request by MariaAga**
Screenshot from 2023-05-31 15-27-21

### CODE REVIEW

**Comment by MariaAga** [comment]
Thanks, added

**Review by adamruzicka — APPROVED** [review]
LGTM

**Review by pondrejk — APPROVED** [review]

**Comment by pondrejk** [comment]
Checked on Sat 6.14 + packit rpm, everything looks all right

**Comment by adamruzicka** [comment]
Thank you @MariaAga & @pondrejk !

**Pull request merged**
