### PR TITLE
Fixes #25127 - fix template loading from task

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by adamruzicka** [comment]
[test]

**Comment by adamruzicka** [comment]
This needs a rebase to make the tests pass

**Comment by ares** [comment]
rebased

**Comment by adamruzicka** [comment]
[test]

**Comment by adamruzicka** [comment]
[test foreman_remote_execution]

**Comment by adamruzicka** [comment]
@ares could you please rebase this once more?

**Comment by iNecas** [comment]
Rebased version opened in https://github.com/theforeman/foreman_remote_execution/pull/400

**Comment by iNecas** [comment]
Merged in https://github.com/theforeman/foreman_remote_execution/pull/400

**Pull request closed without merging**
