### PR TITLE
Fixes #36785 - Show permission error page for job wizard

### PR DESCRIPTION
**Pull request by kmalyjur**
Depends on https://github.com/theforeman/foreman/pull/9902

It is showing missing permissions needed on the `/job_invocations/new` page. The "Proceed Anyway" button lets you look at the wizard even though it won't be working properly.
image

On the "Category and template" step it shows a warning alert if view_job_templates permission is missing:
image

On the "Target hosts and inputs" step it shows a warning alert if view_hosts permission is missing:
image

### CODE REVIEW

**Comment by ofedoren** [comment]
Well, quickly looking at the way we have implemented access control, it seems we only check for one permission per one action. I guess that's why you don't have missing permissions if at least one of them are present. Currently it seems if we add the action into multiple permission blocks, it would treat it as "at least one of those permissions allow this action", which is quite opposite you want to achieve.

As a solution I'd suggest:
 - Either show errors on each requested action (such as loading the page, checking for categories, etc). For loading the page, `create_job_invocations` permission should be enough.
 - Or adjust the whole system to be able to check for multiple permissions for one action.
 
But that's just my observations, @adamruzicka, did I miss anything?

**Comment by adamruzicka** [comment]
Yeah, that's in line with what I've seen.  Out of the two options you suggested I'd vote for the second. There are ~five permissions you really need to be able to trigger a job and I'd prefer not getting to the form at all if I'm missing any rather than seeing the form which bunch of unauthorized errors all over the place. Otoh, and maybe that's just me being pessimistic, I'm pretty sure that there's a part of the wider foreman ecosystem which relies on the current behavior when any permission suffices

**Comment by ares** [comment]
The question is, should we even allow user to get "create_job_invocations" permission without all other 4 required ones? Should it implicitly add these? Should we have any validations? I know this would open a can of worms by introducing dependency between permissions, but from user perspective, I don't want to be able to define meaningless combinations of permissions. With more complex wizards, we'll get to similar situations more often.

**Comment by ofedoren** [comment]
Should we then actually kinda enforce using predefined roles? Which can contain all the needed perms?

**Comment by kmalyjur** [comment]
I've updated the PR to be ready for review. The permissions are taken from a new API (https://github.com/theforeman/foreman/pull/9902). Could anyone please take a look at it?

**Review by pondrejk — APPROVED** [review]
ack, checked on stream snap 38 + packit for this and the dependency PR

**Comment by pondrejk** [comment]
I noticed that it takes a bit of time to display the permission denied panel, first the wizard is displayed, then the panel hops in. But that is just a minor annoyance, otherwise works as described

**Comment by kmalyjur** [comment]
> I noticed that it takes a bit of time to display the permission denied panel, first the wizard is displayed, then the panel hops in. But that is just a minor annoyance, otherwise works as described

Thanks for the review. You're right about this - I kinda ignored it, but if it's too annoying, I can for sure add a "loading" page instead of it in the future.

**Review by adamruzicka — COMMENTED** [review]
Could you please bump the required foreman version in engine.rb to 3.10? Otherwise LGTM

**Review by adamruzicka — APPROVED** [review]
Works like a charm

**Comment by adamruzicka** [comment]
Thank you @kmalyjur , @ofedoren, @ares & @pondrejk !

**Pull request merged**
