### PR TITLE
Fixes #34132 - change default template to the new template name

### PR DESCRIPTION
**Pull request by ezr-ondrej**
We've changed the name of the default template in core, so we also need to change the default.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
We need #677 for the rubocop to pass.

**Comment by adamruzicka** [comment]
The rubocop PR went in, could you rebase please?

**Comment by ezr-ondrej** [comment]
And :green_apple:

**Review by adamruzicka — APPROVED** [review]

**Comment by adamruzicka** [comment]
Thank you @ezr-ondrej !

**Pull request merged**
