### PR TITLE
fixes #12269 - only show rerun failed when there's failed tasks

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
@iNecas How about this one for Iteration 3 too?

**Comment by iNecas** [comment]
Tested and works great. I know @ares  preference is rather to disable the buttons than hiding them (as even if everything works, you know that you could rerun if something went wrong).

**Comment by stbenjam** [comment]
That makes sense, its less confusing than magically disappearing buttons.

Updated

**Comment by iNecas** [comment]
ACK! Tested and works for me

**Comment by stbenjam** [comment]
Thanks!

**Pull request merged**
