### PR TITLE
Fixes #13461 - add preview information to template context

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by stbenjam** [comment]
APJ

**Comment by iNecas** [comment]
I'm curious more about the use case for this? An example?

**Comment by stbenjam** [comment]
The way I read @ares' issue was a very advanced user who knows ruby may want to do something crazy.

What if you had a template that called one of the proxy API's, say `::ProxyAPI::Realm` to create a record in IPA w/ the one-time password, and then rendered a template to call `ipa-client-install` via remote execution with the retrieved OTP?

**Comment by stbenjam** [comment]
So you could have a template like this - I actually think it's a quite cool idea:

```erb
<%
  otp = if @preview
           '$[OTP]'
         else
           api = ::ProxyAPI::Realm.new(:url => SmartProxy.find_by(name: 'realm-proxy.example.com'))
           otp = api.create(:hostname => @host.fqdn)
         end
%>

ipa-client-install -w <%= otp %>
```

**Comment by iNecas** [comment]
I see, and yes, that is interesting :)

**Comment by ares** [comment]
hey, no spoilers! :-) but yeah, @stbenjam :dart: 

another usecases that came to my mind - you may want to hide sensitive info, e.g. private key that you distribute (I know, not a good idea anyway) and we could use it to hide `die()` helpers, public key content etc in preview until we have folding for snippets

maybe a better approach would be to add macro like
```
preview_stub('stub text') do
  $crazy_and_dangerous_stuff
end
```

maybe I'll wrap it into helper at least?

**Comment by ares** [comment]
I've added a `preview?` wrapper/macro to avoid using variables, please take another look.

**Comment by adamruzicka** [comment]
Looks good to me and works well.

I sort of like the idea of `preview_stub(placeholder = '', &block)` macro, considering probably all usages of this will be in the form of
```ruby
if preview?
  something # Or possibly nothing at all
else
  dragons_n_stuff
end
```

**Comment by ares** [comment]
when I added the macro with block I quickly realized that string will be usually too long, keeping it as simple `preview?` method gives the biggest flexibility a better readability

**Comment by adamruzicka** [comment]
Ok, no arguing against that

**Comment by ares** [comment]
@adamruzicka so should I consider it as ACK? :-)

**Comment by adamruzicka** [comment]
@ares Definitely :)

**Comment by ares** [comment]
Thanks, merging.

**Pull request merged**
