### PR TITLE
Fixes #35828- remove search workarounds

### PR DESCRIPTION
**Pull request by MariaAga**
For when https://github.com/theforeman/foreman/pull/9277 breaks rex

### CODE REVIEW

**Comment by adamruzicka** [comment]
Could you please bump required foreman version to `>= 3.6`?

**Comment by MariaAga** [comment]
bumped

**Review by adamruzicka — APPROVED** [review]
Not sure why the [action run](https://github.com/theforeman/foreman_remote_execution/actions/runs/3630459004) didn't get linked to the pr.

Aside from github not cooperating, it works well, ACK

**Comment by adamruzicka** [comment]
Thank you @MariaAga !

**Pull request merged**
