### PR TITLE
Fixes #15600 - fix deprecated after: :finisher_hook

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Works like a charm, APJ

**Comment by dLobatog** [comment]
:-1:

**Comment by iNecas** [comment]
The tests started to fail after some foreman change probably, I will look into that in separate PR

**Comment by iNecas** [comment]
The PR for failing tests https://github.com/theforeman/foreman_remote_execution/pull/192

**Comment by iNecas** [comment]
I've moved the commit from https://github.com/theforeman/foreman_remote_execution/pull/192 here

**Comment by ohadlevy** [comment]
bump - any reason not to merge this one? thanks!

**Comment by iNecas** [comment]
@ohadlevy just to see if there is anyone trying the latest-greatest :)

**Pull request merged**
