### PR TITLE
Fixes #17410 - effective user from job invocation on rerun

### PR DESCRIPTION
**Pull request by iNecas**
It also fixes issue with keeping effective user value when the form is
re-rendered.

### CODE REVIEW

**Comment by adamruzicka** [comment]
It indeed makes the effective user "stick" when one refreshes the page or does a rerun, however it still gets lost when selecting another job category. Is it out of scope of the original issue?

**Comment by iNecas** [comment]
I would say it's outside of scope

**Comment by adamruzicka** [comment]
Ok, created [issue 19316](https://projects.theforeman.org/issues/19316) for it. With that out of the way, let's get this in

**Comment by adamruzicka** [comment]
Thanks @iNecas

**Pull request merged**
