### PR TITLE
Fixes #21668 - Resilience

### PR DESCRIPTION
**Pull request by adamruzicka**
requires:
- [x] https://github.com/theforeman/foreman-tasks/pull/298
- [x] https://github.com/theforeman/smart_proxy_dynflow/pull/40

### CODE REVIEW

**Comment by adamruzicka** [comment]
[test]

**Comment by iNecas** [comment]
Rebase please: this will also trigger the tests against the very latest rex, which is what we want

**Comment by adamruzicka** [comment]
Rebased

**Comment by iNecas** [comment]
Test failures unrelated.

**Pull request merged**
