### PR TITLE
Fixes #37545 - Fix package_action for dash

### PR DESCRIPTION
**Pull request by m-bucher**
Ubuntu-24.04 defaults to dash

### CODE REVIEW

**Comment by sbernhard** [comment]
I'm sorry @adamruzicka. Markus is right. This is required otherwise it will fail on dash.

**Review by sbernhard — APPROVED** [review]

**Review by adamruzicka — APPROVED** [review]
This is getting a bit unwieldy, but I'll trust you on this.

**Comment by adamruzicka** [comment]
@m-bucher could you please rebase?

**Comment by adamruzicka** [comment]
Thank you @m-bucher & @sbernhard !

**Pull request merged**
