### PR TITLE
Fix issues with rubocop 0.49.1

### PR DESCRIPTION
**Pull request by iNecas**
New Rubocop version, yay (sarcasm)

### CODE REVIEW

**Comment by iNecas** [comment]
Jenkins running at http://ci.theforeman.org/job/test_plugin_pull_request/3781/

**Comment by iNecas** [comment]
Back in 'almost 💚 state' http://ci.theforeman.org/job/test_plugin_pull_request/3796/ :)

**Comment by adamruzicka** [comment]
ACK, let's get this in

**Comment by adamruzicka** [comment]
Thanks @iNecas

**Pull request merged**
