### PR TITLE
Fixes #18851 - provide authorizer to avoid large requests

### PR DESCRIPTION
**Pull request by iNecas**
Otherwise, the authorization calculation could be very slow.

### CODE REVIEW

**Comment by iNecas** [comment]
@ares @adamruzicka mind reviewing?

@ares - any idea how to update the authorization helpers to encourage the developers to use the `authorizer`, shouldn't the authorizer  be required field?

**Comment by ares** [comment]
@iNecas for single link it's usually not needed, I'm not sure whether it wouldn't be too big overhead also such change would break tons of code... maybe logging warning of many similar queries would help?

**Comment by ares** [comment]
From quick look, looks good to me

**Comment by adamruzicka** [comment]
Code looks good and it seems to work, however I didn't have enough time to measure how much this helps. Do you have some data on it @iNecas ?

**Comment by beav** [comment]
I have a repro system that I can test with, I'll test today for before/after timings.

**Comment by beav** [comment]
before:
```
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (3400.4ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (2679.1ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (2641.5ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (2900.0ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (1.1ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (3103.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (2773.9ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.5ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (3043.8ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (3239.7ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (2795.7ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (3098.2ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.5ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (3250.2ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (2746.9ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (2963.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (3123.7ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (2642.4ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (2934.1ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (3122.1ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (2764.6ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (2656.3ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (3614.1ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (2837.9ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (3133.2ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (3288.1ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (2872.3ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.5ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (3135.7ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (3350.8ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (2774.3ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (3605.9ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (2888.4ms)
  Rendered /opt/.../job_invocations/_tab_hosts.html.erb (121426.0ms)
  Rendered /opt/.../job_invocations/show.html.erb within layouts/application (121703.4ms)
  Rendered layouts/_application_content.html.erb (0.2ms)
  Rendered home/_submenu.html.erb (1.1ms)
  Rendered home/_user_dropdown.html.erb (1.1ms)
Read fragment views/tabs_and_title_records-45 (0.1ms)
  Rendered home/_topbar.html.erb (6.0ms) 
  Rendered layouts/base.html.erb (6.7ms) 
Completed 200 OK in 121917ms (Views: 121521.1ms | ActiveRecord: 243.4ms)
```

after:
```
Processing by JobInvocationsController#show as HTML
  Parameters: {"id"=>"43"}
  Rendered /opt/.../job_invocations/_tab_overview.html.erb (202.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (4.5ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.3ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.5ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.1ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.1ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.1ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.1ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.0ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.1ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.1ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.1ms)
  Rendered /opt/.../job_invocations/_host_name_td.html.erb (0.4ms)
  Rendered /opt/.../job_invocations/_host_status_td.html.erb (0.3ms)
  Rendered /opt/.../job_invocations/_host_actions_td.html.erb (1.0ms)
  Rendered /opt/.../job_invocations/_tab_hosts.html.erb (50.2ms)
  Rendered /opt/.../job_invocations/show.html.erb within layouts/application (315.1ms)
  Rendered layouts/_application_content.html.erb (0.2ms)
  Rendered home/_submenu.html.erb (1.0ms)
  Rendered home/_user_dropdown.html.erb (1.0ms)
Read fragment views/tabs_and_title_records-45 (0.1ms)
  Rendered home/_topbar.html.erb (7.1ms)
  Rendered layouts/base.html.erb (7.8ms)
Completed 200 OK in 534ms (Views: 271.3ms | ActiveRecord: 106.0ms)

```

**Comment by iNecas** [comment]
The failures in tests seem unrelated, pulling the changes is

**Pull request merged**
