### PR TITLE
Fixes #19360 - avoid conflicts with minitest methods

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by iNecas** [comment]
Master is red, therefore the CI doesn't run the tests, I've triggered them manually http://ci.theforeman.org/job/test_plugin_pull_request/3633/

**Comment by iNecas** [comment]
Still some issues there, fixing and running again in http://ci.theforeman.org/job/test_plugin_pull_request/3637/

**Comment by adamruzicka** [comment]
@iNecas all the tests are still failing, this time because of rubocop

> Error: The `Rails/DefaultScope` cop no longer exists.

**Comment by iNecas** [comment]
Oh my, fixing or disabling those that didn't make sense to me, lets see now http://ci.theforeman.org/job/test_plugin_pull_request/3642/

**Comment by iNecas** [comment]
boy, what have I done to deserve this: gazzilion of unrelated issues in jenkins I can't reproduce on my side. Adding some debugging and trying again http://ci.theforeman.org/job/test_plugin_pull_request/3642/#showFailuresLink

**Comment by bastilian** [comment]
@iNecas when i investigated and found http://projects.theforeman.org/issues/19396, it wasn't reproducible until i remove Gemfile.lock and updated gems. just in case you haven't yet.

also, i think there is something weird going on with tests.

**Comment by iNecas** [comment]
The strangest thing is that I see a number of strange issues in foreman tests here http://ci.theforeman.org/job/test_plugin_pull_request/3648/database=mysql,label=fast,ruby=2.3/console, while the things are green on similar PR on foreman-tasks  http://ci.theforeman.org/job/test_plugin_pull_request/3647

**Comment by bastilian** [comment]
@iNecas as i said... something weird is going on. at the moment i'm reluctant to trust any failure or success.

**Comment by iNecas** [comment]
I've tried to remove some custom stuff in our test helper that could potentially conflict with the foreman's tests (https://github.com/theforeman/foreman_remote_execution/pull/243/commits/e08f3fd25fe1348716037d2c4408ace07d262b0a): lets see if it helps anyhow. http://ci.theforeman.org/job/test_plugin_pull_request/3650/

**Comment by iNecas** [comment]
So I hope I finally cracked the issues we had here. It's a combination of https://github.com/theforeman/foreman/pull/4490 + https://github.com/rubiety/validates_lengths_from_database/pull/17, lets have it confirmed by http://ci.theforeman.org/job/test_plugin_pull_request/3664/

**Comment by ares** [comment]
not there yet :-)

```
== 20140219183345 AddTaxonomySearchesToFilter: migrating ======================
-- add_column(:filters, :taxonomy_search, :text)
   -> 0.0298s
[32m2017-04-28T05:38:26[0m  [[36mapp[0m] [D] String does not start with the prefix 'encrypted-', so Setting::General fix_db_cache was not decrypted
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `[]' for nil:NilClass
/usr/local/rvm/gems/ruby-2.4.0@test_plugin_pull_request-0/gems/validates_lengths_from_database-0.5.1/lib/validates_lengths_from_database.rb:37:in `validate_lengths_from_database'
/usr/local/rvm/gems/ruby-2.4.0@test_plugin_pull_request-0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.4.0@test_plugin_pull_request-0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/rvm/gems/ruby-2.4.0@test_plugin_pull_request-0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/rvm/gems/ruby-2.4.0@test_plugin_pull_request-0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
/usr/local/rvm/gems/ruby-2.4.0@test_plugin_pull_request-0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.4.0@test_plugin_pull_request-0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.4.0@test_plugin_pull_request-0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_validate_callbacks'
/usr/local/rvm/gems/ruby-2.4.0@test_plugin_pull_request-0/gems/activemodel-4.2.8/lib/active_model/validations.rb:399:in `run_validations!'
/usr/local/rvm/gems/ruby-2.4.0@test_plugin_pull_request-0/gems/activemodel-4.2.8/lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
```

**Comment by iNecas** [comment]
I know about that (see https://github.com/rubiety/validates_lengths_from_database/pull/17#issuecomment-297921192), working on a fix

**Comment by iNecas** [comment]
Here we go https://github.com/rubiety/validates_lengths_from_database/pull/18

**Comment by iNecas** [comment]
foreman bookmarks issue fixed upstream, validates_lengths_from_database fixed upstream, the tests against custom branch went green, trying one more time now against develop, but should be good to go http://ci.theforeman.org/job/test_plugin_pull_request/3667/

**Comment by adamruzicka** [comment]
@iNecas There are still some failing tests :/

**Comment by iNecas** [comment]
These seem to be some intermittent issues not related to remote execution. I'm merging this code now: lets see how it behaves in master tests

**Comment by iNecas** [comment]
Look ma, look pa, green tests :) http://ci.theforeman.org/job/test_plugin_matrix/3028/

**Comment by adamruzicka** [comment]
Well done 👏

**Pull request merged**
