### PR TITLE
Fixes #20283 - Always populate host table

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by iNecas** [comment]
Tests running at http://ci.theforeman.org/job/test_plugin_pull_request/3893/

**Comment by iNecas** [comment]
Tested and works well, waiting for jenkins

**Comment by adamruzicka** [comment]
Mr. Jenkins approves

**Comment by iNecas** [comment]
Wooow, actually green tests :) So do I then

**Pull request merged**
