### PR TITLE
Refs #28668 - remove tfm/env and use tfm/vendor >= 4

### PR DESCRIPTION
**Pull request by sharvit**
It might be the reason https://github.com/theforeman/foreman-packaging/pull/4347 is failing.

### CODE REVIEW

**Comment by ekohl** [comment]
Out of curiosity, what makes you think that this would help?

**Comment by sharvit** [comment]
> Out of curiosity, what makes you think that this would help?

The tfm/env asks for builder v3 to be there. It should be ignored in packaging AFAIK but the packaging is still a black box for me :/
https://github.com/theforeman/foreman-js/blob/v3.12.0/packages/env/package.json#L26-L28

**Comment by adamruzicka** [comment]
The tests are green, let's get this in

**Comment by adamruzicka** [comment]
Will someone try building the package with this locally or should I do a full release?

**Pull request merged**
