### PR TITLE
fixes #14752 - only add index once in features migration

### PR DESCRIPTION
**Pull request by stbenjam**
~~Not intending this one to get merged, just opened for running tests. Really should be part of #173~~ Nevermind, we can use this PR to get tests going again.

### CODE REVIEW

**Comment by stbenjam** [comment]
Index was getting added twice in Rails 4.2, which resulted in:

``

Index name 'index_remote_execution_features_on_label' on table 'remote_execution_features' already exists/usr/local/rvm/gems/ruby-2.0.0-p353@test_plugin_pull_request-2/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:954:in `add_index_options'
```

**Comment by ares** [comment]
APJ

**Comment by domcleal** [comment]
Please note that the tests may appear to be passing, but a failure loading your tests is being ignored - probably due to the way the task is enhanced.  (If you fix this somehow, please fix it also in the plugin template.)

<pre>
/var/lib/workspace/workspace/test_plugin_pull_request/database/postgresql/label/fast/ruby/1.9.3/plugin/test/test_plugin_helper.rb:11:in `<top (required)>': uninitialized constant DatabaseCleaner (NameError)
	from /var/lib/workspace/workspace/test_plugin_pull_request/database/postgresql/label/fast/ruby/1.9.3/plugin/test/functional/api/v2/foreign_input_sets_controller_test.rb:1:in `require'
	from /var/lib/workspace/workspace/test_plugin_pull_request/database/postgresql/label/fast/ruby/1.9.3/plugin/test/functional/api/v2/foreign_input_sets_controller_test.rb:1:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p392@test_plugin_pull_request-0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:10:in `require'
	from /usr/local/rvm/gems/ruby-1.9.3-p392@test_plugin_pull_request-0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /usr/local/rvm/gems/ruby-1.9.3-p392@test_plugin_pull_request-0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p392@test_plugin_pull_request-0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in `block in <main>'
	from /usr/local/rvm/gems/ruby-1.9.3-p392@test_plugin_pull_request-0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /usr/local/rvm/gems/ruby-1.9.3-p392@test_plugin_pull_request-0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
-- execute("SET CONSTRAINTS ALL DEFERRED;")
   -> 0.0021s
rake aborted!
</pre>

**Comment by stbenjam** [comment]
@domcleal Well we can require database_cleaner directly, and that should fix this problem.

Not sure how to fix jenkins ignoring the failure though... `rake test:foreman_remote_execution` returns 1, does it not when its just enhancing the test task?

**Comment by stbenjam** [comment]
Hmph, I wonder how long tests really haven't been running. 

```
/usr/local/rvm/gems/ruby-2.0.0-p353@test_plugin_pull_request-0/gems/activemodel-4.2.6/lib/active_model/validations.rb:157:in `block in validate': Unknown key: :presence. Valid keys are: :on, :if, :unless, :prepend. Perhaps you meant to call `validates` instead of `validate`? (ArgumentError)
```

**Comment by stbenjam** [comment]
Oh, all kinds of test failures now that they're actually running :cry:

**Comment by domcleal** [comment]
> Not sure how to fix jenkins ignoring the failure though... rake test:foreman_remote_execution returns 1, does it not when its just enhancing the test task?

The change at https://github.com/theforeman/foreman_plugin_template/pull/14 should do it.

**Comment by stbenjam** [comment]
@domcleal Awesome, thanks!

Closing this one, as we moved it all over to https://github.com/theforeman/foreman_remote_execution/pull/173.

**Pull request closed without merging**
