### PR TITLE
Fixes #35343 - make sure to install kernel updates

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Review by adamruzicka — APPROVED** [review]
Huh, that's quite surprising behavior on `apt-get`'s side. Let's get this in

**Comment by adamruzicka** [comment]
Thank you @sbernhard !

**Comment by evgeni** [comment]
One shall not use `apt` in scripts (which is what we do here).

It even says so if you do:

```console
# apt install wget -y | cat

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```

The correct way here would be to override `action` to be `install`, as `apt-get install <existing package>` does the right thing.

Or you need to call `apt-get dist-upgrade` to allow installing new packages, which `apt-get upgrade` does not.

**Comment by evgeni** [comment]
Alternatively you should be able to set `APT::Get::Upgrade-Allow-New=true` (I think)

**Pull request merged**
