### PR TITLE
Fixes #28647 - Validate metadata for foreign inputs

### PR DESCRIPTION
**Pull request by xprazak2**
(cherry picked from commit 82a92f6a7e5ba92ed852402a1e4c3622b51961c7)

### CODE REVIEW

**Comment by adamruzicka** [comment]
APJ

**Comment by xprazak2** [comment]
Smart vars test will not pass as the tests run against develop...

**Comment by adamruzicka** [comment]
Tests are passing locally, ACK

**Comment by adamruzicka** [comment]
Thank you @xprazak2 !

**Pull request merged**
