### PR TITLE
Use GitHub actions as CI

### PR DESCRIPTION
**Pull request by ezr-ondrej**

### CODE REVIEW

**Comment by adamruzicka** [comment]
So we will have hound, travis, jenkins and gh actions?

**Comment by ezr-ondrej** [comment]
> So we will have hound, travis, jenkins and gh actions?

The idea is being we have only gh-actions :)
GH-actions can do it all. but definitelly we can rule out travis and hound (see `rubocop` task and `test_js` task). we can leave just those two for now.
Unless we insist on Hound comenting the code, what I presonaly don't like too much :thinking:

**Comment by adamruzicka** [comment]
Could I see the action in action somewhere? I don't see it being run here nor in your fork

**Comment by ezr-ondrej** [comment]
I've enabled it on push to demostrate: https://github.com/ezr-ondrej/foreman_remote_execution/actions/runs/122023055

**Comment by adamruzicka** [comment]
Could we get it green before we merge it?

**Comment by ezr-ondrej** [comment]
I've fixed up tests to go :green_apple: https://github.com/ezr-ondrej/foreman_remote_execution/actions/runs/122422695 This is the same code, just with removed `push` we still run ruby tests, but I believe it could be worth to try it out alongside Jenkis for a while.

**Comment by adamruzicka** [comment]
Thank you @ezr-ondrej !

**Pull request merged**
