### PR TITLE
Fixes #24159 - Non admin user failed to render included template

### PR DESCRIPTION
**Pull request by ranjan**

### CODE REVIEW

**Comment by adamruzicka** [comment]
I see why this didn't work before. Could we get a test for it?

**Comment by ranjan** [comment]
@adamruzicka My dev environment for remote-execution is not yet ready, So for now its not possible to add test cases :disappointed:

**Comment by adamruzicka** [comment]
Added a test to this PR, @iNecas could you please take a look?

**Comment by iNecas** [comment]
Thanks @adamruzicka and @ranjan

**Pull request merged**
