### PR TITLE
Fixes #21242 - revert using prepend instaed of alias_method_chain

### PR DESCRIPTION
**Pull request by iNecas**
This is only intended for the 1.15 and 1.16, the nightlies should
keep the change and the proper fix should be done in Katello
to make it work again.

### CODE REVIEW

**Comment by adamruzicka** [comment]
Is there a way to make the tests pass?

**Comment by iNecas** [comment]
Running against 1.16 stable (http://ci.theforeman.org/job/test_plugin_pull_request/4193/) and 1.15-stable (http://ci.theforeman.org/job/test_plugin_pull_request/4194/)

**Comment by evgeni** [comment]
The patch on top of 1.3.4 makes it work fine again with Foreman 1.15 and Katello 3.4, thanks!

**Comment by iNecas** [comment]
1.3.5 released and packaging PR opened here https://github.com/theforeman/foreman-packaging/pull/1852

**Pull request merged**
