### PR TITLE
Fixes #11724 - load the job template

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by iNecas** [comment]
It it supposed to work with foreman 1.10? 
new-template-preview

**Comment by ares** [comment]
Interesting, I didn't tested with 1.10 but I don't see anything incompatible. Does this happen for new templates or when you edit existing one (I guess the first case)?

**Comment by iNecas** [comment]
First case

**Comment by ares** [comment]
@iNecas this should work with 1.10 and develop, would you mind retesting?

**Comment by iNecas** [comment]
Works nicely. One idea: nicer error message when template inputs are defined, explaining that the template needs to be saved in order to work (or fixing the inputs case as well:)

**Comment by ares** [comment]
Like this?

**Comment by iNecas** [comment]
works for me, ACK

**Comment by ares** [comment]
Thanks, merging

**Pull request merged**
