### PR TITLE
Fixes #33397 - Propagate validation errors from triggering

### PR DESCRIPTION
**Pull request by xprazak2**
A minimal solution leveraging the existing errors flattener.

### CODE REVIEW

**Review by adamruzicka — APPROVED** [review]
Let's get this in as-is. We can always revisit it later

**Comment by MariaAga** [comment]
This also solved this issue: https://projects.theforeman.org/issues/35076

**Comment by adamruzicka** [comment]
Rebased for a good measure, waiting for tests to pass before merging.

**Comment by adamruzicka** [comment]
Thank you @xprazak2 & @MariaAga !

**Pull request merged**
