### PR TITLE
Fixes #30933, #30935 - Type=search input fixes

### PR DESCRIPTION
**Pull request by adamruzicka**
requires:
- [ ] ~~https://github.com/theforeman/foreman/pull/8035~~
- [x] https://github.com/theforeman/foreman/pull/8060

### CODE REVIEW

**Comment by adamruzicka** [comment]
Dropped the second commit. It shouldn't be needed after https://github.com/theforeman/foreman/pull/8060 gets in

**Review by ezr-ondrej — APPROVED** [review]
Make sense :+1: 

Just a thought for feature improvements:
We have ReportComposer in the core, that tries to acomplish similar task as JobInvocationComposer, would it be worth to make an unified ancestor? :thinking:

**Comment by adamruzicka** [comment]
Not sure if they have all that much in common from the top of my head, but worth investigating in the future

**Review by shiramax — APPROVED** [review]
I've tested the PR and it's working great.

**Comment by ezr-ondrej** [comment]
The core PR is in, lets merge this :)
Thanks @adamruzicka and @shiramax for testing! :+1:

**Pull request merged**
