### PR TITLE
Fixes #12538 - Add support for rubocop 0.35.1 - update after rebase

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by stbenjam** [comment]
We will be on Rails 4 shortly

**Comment by stbenjam** [comment]
When we're ready - https://github.com/theforeman/foreman-infra/pull/205

**Comment by iNecas** [comment]
The jenkins job against develop here http://ci.theforeman.org/job/test_plugin_pull_request/2133/

**Comment by stbenjam** [comment]
https://github.com/theforeman/foreman_remote_execution/pull/126 to fix mass assignment.

APJ for this one

**Comment by stbenjam** [comment]
Moved to https://github.com/theforeman/foreman_remote_execution/pull/126, to get 1.11 fixes in 1 PR

**Pull request closed without merging**
