### PR TITLE
 Fixes #23042 - Use new cleaner helpers 

### PR DESCRIPTION
**Pull request by adamruzicka**
This should also fix failing tests on sqlite

### CODE REVIEW

**Comment by adamruzicka** [comment]
Tests running here http://ci.theforeman.org/job/test_plugin_pull_request/4833/

**Comment by mmoll** [comment]
:broken_heart:

**Comment by adamruzicka** [comment]
Tests are running here http://ci.theforeman.org/job/test_plugin_pull_request/4834/

**Comment by mmoll** [comment]
:green_heart:

**Comment by iNecas** [comment]
Thanks @adamruzicka

**Pull request merged**
